---
apiVersion: v1
kind: Service
metadata:
  name: miniature-dollop
  labels:
    name: miniature-dollop
spec:
  ports:
    # the port that this service should serve on
  - port: 4000
    targetPort: 4000
  selector:
    name: miniature-dollop